/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import Bean.DataDistributor;
import java.awt.*;
import koneksi.*;
import javax.swing.*;

import Tabel.*;

import java.awt.event.*;
import java.sql.*;


public class FormDistributor extends javax.swing.JFrame {
private Object tabel;
    private TabelDataDistributor ModelDataDistributor;
    private koneksi conn;
    /**
     * Creates new form FormDistributor
     */
    public FormDistributor() {
        initComponents();
         Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize=this.getSize();
        if(frameSize.height>screenSize.height){
            frameSize.height=screenSize.height;
        }
        if(frameSize.width>screenSize.width){
            frameSize.width=screenSize.width;            
        }
        this.setLocation((screenSize.width-frameSize.width)/2,
                (screenSize.height=screenSize.height)/4);
        ModelDataDistributor = new TabelDataDistributor();
        tabledistributor.setModel(ModelDataDistributor);
        conn = new koneksi();
        tampil();
        SetEditOff();
    }
 private void tampil(){
        try{
            int baris =tabledistributor.getRowCount();
            for (int i =0; i < baris; i++){
                ModelDataDistributor.delete(0,baris);
            }
            String SQL = "select * from tbldistributor";
            ResultSet rs = conn.getData(SQL);
            while (rs.next()) {
                DataDistributor distributor = new DataDistributor();
                distributor.setIdDistributor (rs.getString(1));
                distributor.setNamaDistributor (rs.getString(2));
                distributor.setAlamat (rs.getString(3));
                distributor.setKotaAsal (rs.getString(4));
                distributor.setEmail (rs.getString(5));
                distributor.setTelepon (rs.getString(6));
                ModelDataDistributor.add(distributor);
            }
        } catch (SQLException ex) {
            System.err.print(ex);
            }
    }
    int row = 0;
    public void TampilText(){
            row = tabledistributor.getSelectedRow();
            DataDistributor bDistributor = ModelDataDistributor.get(row);
            iddistributor.setText(bDistributor.getIdDistributor());
            namadistributor.setText(bDistributor.getNamaDistributor());
            alamat.setText(bDistributor.getAlamat());
            kotaasal.setText(bDistributor.getKotaAsal());
            email.setText(bDistributor.getEmail());
            telpon.setText(bDistributor.getTelepon());
            save.setEnabled(false);
            SetEditOn();
            }
    
    public void BersihData(){
        iddistributor.setText("");
        namadistributor.setText("");
        alamat.setText("");
        kotaasal.setText("");
        email.setText("");
        telpon.setText("");
        }
    
    public void SetEditOff(){
        iddistributor.setEnabled(false);
        namadistributor.setEnabled(false);
        alamat.setEnabled(false);
        kotaasal.setEnabled(false);
        email.setEnabled(false);
        telpon.setEnabled(false);
        save.setEnabled(false);
        delete.setEnabled(false);
        update.setEnabled(false);           
        add.setEnabled(true);
    
    }

    public void SetEditOn(){
        iddistributor.setEnabled(true);
        namadistributor.setEnabled(true);
        alamat.setEnabled(true);
        kotaasal.setEnabled(true);
        email.setEnabled(true);
        telpon.setEnabled(true);        
        save.setEnabled(true);
        delete.setEnabled(true);
        update.setEnabled(true);           
        add.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        iddistributor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namadistributor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledistributor = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        kotaasal = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telpon = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        close = new javax.swing.JButton();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Form Distributor");

        jLabel2.setText("id distributor :");

        iddistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddistributorActionPerformed(evt);
            }
        });

        jLabel3.setText("nama distributor :");

        tabledistributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledistributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledistributorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabledistributor);

        jLabel4.setText("alamat :");

        jLabel5.setText("kota asal :");

        jLabel6.setText("email :");

        jLabel7.setText("telpon :");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        add.setText("Add New");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iddistributor)
                            .addComponent(namadistributor)
                            .addComponent(alamat)
                            .addComponent(kotaasal)
                            .addComponent(email)
                            .addComponent(telpon, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(add)
                        .addGap(18, 18, 18)
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(cancel)
                        .addGap(18, 18, 18)
                        .addComponent(close)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(iddistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namadistributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kotaasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(save)
                    .addComponent(update)
                    .addComponent(delete)
                    .addComponent(cancel)
                    .addComponent(close))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         String KJ=iddistributor.getText();
        String J=namadistributor.getText();
        String A=alamat.getText();
        String K=kotaasal.getText();
        String E=email.getText();
        String T=telpon.getText();
        if ((KJ.isEmpty()) | (J.isEmpty()) | (A.isEmpty()) | (K.isEmpty()) | (E.isEmpty()) | (T.isEmpty())){
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong,"+
                "silahkan dilengkapi");
            iddistributor.requestFocus();
        }else{
            try{
                String SQL = "update tbldistributor set "
                + " namadistributor ='"+namadistributor.getText()+"',"
                + " alamat ='"+alamat.getText()+"',"
                + " kotaasal ='"+kotaasal.getText()+"',"
                + " email ='"+email.getText()+"',"
                + " telepon ='"+telpon.getText()+"' where"
                + " iddistributor = '"+iddistributor.getText()+"'";

                conn.query(SQL);
                tampil();
                JOptionPane.showMessageDialog(null, iddistributor.getText()+
                    "Berhasil Diubah");
                BersihData();
                SetEditOff();
                add.setEnabled(true);
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String KJ=iddistributor.getText();
        String J=namadistributor.getText();
        String A=alamat.getText();
        String K=kotaasal.getText();
        String E=email.getText();
        String T=telpon.getText();
        if ((KJ.isEmpty()) | (J.isEmpty()) | (A.isEmpty()) | (K.isEmpty()) | (E.isEmpty()) | (T.isEmpty())){
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong,"+
                "silahkan dilengkapi");
            namadistributor.requestFocus();

        }else {
            try {
                String SQL = "delete from tbldistributor where "
                + "iddistributor = '"+iddistributor.getText()+"'";
                conn.query(SQL);
                tampil();
                JOptionPane.showMessageDialog(null,
                    "data dihapus");
                BersihData();
                SetEditOff();
                add.setEnabled(true);
            } catch (Exception ex){
                System.err.println(ex);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
         BersihData();
        SetEditOff();
    }//GEN-LAST:event_cancelActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(null,"This application will be close"+
            "\n if you pass button OK","information",
            JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)
        ==JOptionPane.OK_OPTION){
        this.dispose();
        }

    }//GEN-LAST:event_closeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
      BersihData();
        iddistributor.requestFocus();
        save.setEnabled(true);
        SetEditOn();
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
       String KJ=iddistributor.getText();
        String J=namadistributor.getText();
        String A=alamat.getText();
        String K=kotaasal.getText();
        String E=email.getText();
        String T=telpon.getText();
        
        if ((KJ.isEmpty()) | (J.isEmpty()) | (A.isEmpty()) | (K.isEmpty()) | (E.isEmpty()) | (T.isEmpty())){
            JOptionPane.showMessageDialog(null,"data tidak boleh kosong, "+
                "silahkan dilengkapi");
            iddistributor.requestFocus();

        }else{
            try{
                String SQL = "insert into tbldistributor values ("
                + "'"+iddistributor.getText()+"',"
                + "'"+namadistributor.getText()+"',"
                + "'"+alamat.getText()+"',"
                + "'"+kotaasal.getText()+"',"
                + "'"+email.getText()+"',"
                + "'"+telpon.getText()+"'"
                + ")";
                conn.query(SQL);
                tampil();
                JOptionPane.showMessageDialog(null, iddistributor.getText()+
                    "Berhasil Disimpan");
                BersihData();
                SetEditOff();
                add.setEnabled(true);
            } catch (Exception ex){
                System.err.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void iddistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddistributorActionPerformed

    private void tabledistributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledistributorMouseClicked
        // TODO add your handling code here:
          if (evt.getClickCount()==1){
            TampilText();
        } 
    }//GEN-LAST:event_tabledistributorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new HalamanUtama().show();
        this.dispose();              
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDistributor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDistributor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton cancel;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JTextField iddistributor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kotaasal;
    private javax.swing.JTextField namadistributor;
    private javax.swing.JButton save;
    private javax.swing.JTable tabledistributor;
    private javax.swing.JTextField telpon;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
